# Generated by Django 4.2.29 on 2026-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1097_add_is_pending_deletion_to_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadeletionrequest",
            name="execution_mode",
            field=models.CharField(
                choices=[("immediate", "Immediate"), ("deferred", "Deferred")],
                default="immediate",
                help_text="Picked by ClickHouse Team at approval time. Immediate: run a dedicated delete mutation now. Deferred: queue event UUIDs into adhoc_events_deletion so the scheduled deletes_job drains them. Only honored for event_removal.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datadeletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("in_progress", "In Progress"),
                    ("queued", "Queued"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
    ]
